export const funnyNonsenseQuotes: string[] = [
  "Discipline today creates the freedom you dream of tomorrow.",
  "Small progress every day builds unstoppable confidence.",
  "Consistency turns ordinary effort into extraordinary results.",
  "Focus on growth, not perfection.",
  "Your future is built by what you do daily.",
  "Stay patient. Stay consistent. Stay humble.",
  "Great things take time — keep going.",
  "Your only competition is who you were yesterday.",
  "Hard days create strong minds.",
  "Keep showing up even when no one is watching.",
  "Dream big. Start small. Act now.",
  "Success begins with self-belief.",
  "Do it with passion or not at all.",
  "The version of you that succeeds is built daily.",
  "Make yourself proud.",
  "Your mindset shapes your reality.",
  "Stay focused. Your time is coming.",
  "Progress, not excuses.",
  "Be stronger than your strongest excuse.",
  "Growth begins at the end of comfort.",

  // Spiritual + philosophical (neutral)
  "Do your work with full heart and let results follow.",
  "Detach from outcomes, focus on effort.",
  "Peace comes when expectations reduce.",
  "A calm mind creates a powerful life.",
  "What you think, you become.",
  "Master the mind and you master life.",
  "Silence strengthens clarity.",
  "Patience and persistence shape destiny.",
  "Inner peace is the real success.",
  "Control actions, not outcomes.",
  "When intention is pure, paths become clear.",
  "Balance in mind brings balance in life.",
  "Self-control is true strength.",
  "Purpose gives direction to effort.",
  "Clarity comes from discipline.",
  "Act without fear. Learn without ego.",
  "Still mind. Strong actions.",
  "Detach from worry. Attach to effort.",
  "Your duty is effort, not overthinking results.",
  "Stay steady in success and failure.",

  // Short website UI quotes
  "Built with purpose.",
  "Driven by discipline.",
  "Create. Improve. Repeat.",
  "Focus. Build. Grow.",
  "Consistency wins.",
  "Calm mind. Strong life.",
  "Progress every day.",
  "Dream. Work. Achieve.",
  "Stay grounded. Aim high.",
  "Evolve daily.",
];
